user nginx;
worker_processes 4;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 10;
    gzip on;

    upstream django_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name localhost;
        charset utf-8;
        access_log /var/log/nginx/access.log;

        location = /health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "healthy\n";
        }

        location / {
            proxy_pass http://django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }
}
